---
- name: configure apache using child playbook
  hosts: server3
  tasks:
    - name: calling multiple child playbooks
      include: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
...
